"""
Deterministic table extraction for the summarization pipeline.

Uses PyMuPDF's page.find_tables() (layout-based; handles ruled AND
borderless tables without the Java runtime that tabula-py/camelot
require). Purpose: surface real table data in summaries as VERBATIM
structured text, instead of the previous behavior of detecting flattened
table rows in the prose stream, deleting them, and telling the user to
go read the original document.

Design (mirrors the pipeline's other deterministic extractors):

- No LLM involvement: cells are taken directly from the PDF layout, so
  the verbatim guarantee holds - nothing here can hallucinate.
- Conservative filters drop 1-row fragments (two-column prose snippets,
  orphan header rows, caption grids misread as tables) and tables whose
  joined text trips the garbage detector (content_quality.py).
- Hard caps on rows per table and tables per document keep a hostile or
  degenerate document from blowing the context window; truncation is
  explicit and noted in the rendered output.
- If find_tables fails or finds nothing, callers fall back to the
  current no-table behavior unchanged (graceful degradation).

Note: tables on pages flagged as interleaved multi-column (see
heading_detection.py) are still worth extracting - find_tables clusters
cells by position, so it recovers the correct column pairing even when
the raw line order alternates.
"""
import pymupdf as fitz  # `fitz` is the old import name; PyMuPDF now ships
                         # it as `pymupdf` and warns on the old name, but
                         # the API is identical, so aliasing it back to
                         # `fitz` avoids renaming every call in this file

from content_quality import is_garbage

# A table with fewer rows/columns than this is almost never a real table
# - it's a two-column prose fragment, an orphan header row, or a caption
# grid (all observed in real PDFs during testing).
_MIN_ROWS = 2
_MIN_COLS = 2

# Individual cell cap: a cell longer than this is prose accidentally
# inside a detected grid, not table data worth quoting verbatim.
_MAX_CELL_CHARS = 300

# Hard caps for rendering. Extraction itself is uncapped so stats stay
# truthful; the renderer truncates with an explicit note.
_MAX_TABLES_PER_DOC = 25
_MAX_ROWS_PER_TABLE = 50


def _clean_cell(text):
    """One table cell -> one sanitized, whitespace-collapsed string."""
    text = (text or "").replace("\x00", "")
    return " ".join(text.split())[:_MAX_CELL_CHARS]


def extract_tables(pdf_path, pages=None):
    """
    All tables found in `pdf_path` (optionally restricted to 0-indexed
    `pages`), as a list of dicts:

        {"page": int, "index": int, "rows": [[cell, cell, ...], ...]}

    Tables with fewer than _MIN_ROWS rows or _MIN_COLS columns, and
    tables whose joined cell text trips the garbage detector, are
    skipped. Returns [] when the file can't be opened, find_tables
    fails, or nothing passes the filters - callers should treat that
    exactly like the previous no-table behavior.
    """
    try:
        doc = fitz.open(pdf_path)
    except Exception:
        return []

    results = []
    try:
        for page_num, page in enumerate(doc):
            if pages is not None and page_num not in pages:
                continue
            try:
                tables = page.find_tables().tables
            except Exception:
                continue
            for index, table in enumerate(tables):
                try:
                    rows = [[_clean_cell(c) for c in row] for row in table.extract()]
                except Exception:
                    continue
                rows = [row for row in rows if any(row)]
                if not rows or len(rows) < _MIN_ROWS or len(rows[0]) < _MIN_COLS:
                    continue
                if is_garbage(" ".join(cell for row in rows for cell in row)):
                    continue
                results.append({"page": page_num, "index": index, "rows": rows})
    finally:
        doc.close()
    return results


def tables_to_markdown(tables):
    """
    Verbatim markdown rendering of extracted tables for the summary's
    "Extracted Table Data" section. First row of each table is used as
    the header row. Pipes in cells are escaped; row/table caps apply
    with explicit truncation notes. Returns '' when there is nothing to
    render.
    """
    if not tables:
        return ""

    parts = [
        "\n### Extracted Table Data (Verbatim)",
        "_The tables below were captured directly from the source layout by "
        "pattern matching, not generated by the model, so the cell values are "
        "guaranteed accurate to the source._",
    ]

    shown = 0
    for table in tables:
        if shown >= _MAX_TABLES_PER_DOC:
            break
        shown += 1

        rows = table["rows"]
        header, body = rows[0], rows[1:]
        parts.append(f"\n**Table {shown} (page {table['page'] + 1}):**")
        parts.append("| " + " | ".join(header) + " |")
        parts.append("| " + " | ".join("---" for _ in header) + " |")

        for row in body[:_MAX_ROWS_PER_TABLE]:
            parts.append("| " + " | ".join(cell.replace("|", "\\|") for cell in row) + " |")
        if len(body) > _MAX_ROWS_PER_TABLE:
            parts.append(f"_...{len(body) - _MAX_ROWS_PER_TABLE} more row(s) truncated._")

    if len(tables) > _MAX_TABLES_PER_DOC:
        parts.append(f"\n_...and {len(tables) - _MAX_TABLES_PER_DOC} more table(s) truncated._")

    return "\n".join(parts)
